sudo: required
services:
  - docker

before_install:
  - docker build -t cryon/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true cryon/react-test npm test

after_success:
  - docker build -t cryon/multi-client ./client
  - docker build -t cryon/multi-nginx ./nginx
  - docker build -t cryon/multi-server ./server
  - docker build -t cryon/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push cryon/multi-client
  - docker push cryon/multi-nginx
  - docker push cryon/multi-server
  - docker push cryon/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-north-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-north-1-370967224695
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
